version: "2"
services:
  google_dyn_dns:
    image: henryse/google_dyn_dns:latest
    ports:
      - 8443:9443
    environment:
      - "HOST=$DOCKER_IP"
      - "LOGSTASH_ENABLED=false"
      - "SERVICE_NAME=google_dyn_dns"
      - "SERVICE_443_CHECK_HTTPS=/health"
      - "SERVICE_TAGS=traefik.enable=true"